config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'
  get 'store/about'

  resources :products do
  	get :who_bought, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: 'store'
end

app/views/layouts/1application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Pragprog Books Online Store</title>
 <%= stylesheet_link_tag "application", media: "all",
 "data-turbolinks-track" => true %>
 <%= javascript_include_tag "application",
 "data-turbolinks-track" => true %>
 <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
 <%= csrf_meta_tag %>
</head>
<body class="<%= controller.controller_name %>">
 <div id="banner">
   <%= image_tag("logo.png") %>
   <%= @page_title || "Pragmatic Bookshelf" %>
 </div>
 <div id="columns">
  <div id="side">
    <div id="cart">
      <% if @cart %>
      <%= render @cart %>
      <% end %>
    </div>
    <ul>
     <li><a href="http://www....">Home</a></li>
     <li><a href="http://www..../faq">Questions</a></li>
     <li><a href="http://www..../news">News</a></li>
     <li><a href="http://www..../contact">Contact</a></li>
   </ul>

   <% if session[:user_id] %>
   <ul>
     <li><%= link_to 'Orders', orders_path %></li>
     <li><%= link_to 'Products', products_path %></li>
     <li><%= link_to 'Users', users_path %></li>
   </ul>
   <%= button_to 'Logout', logout_path, method: :delete %>
   <% end %>
 </div>
 <div id="main">
   <%= yield %>
 </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Pragprog Books Online Store</title>
 <%= stylesheet_link_tag "application", media: "all",
 "data-turbolinks-track" => true %>
 <%= javascript_include_tag "application",
 "data-turbolinks-track" => true %>
 <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
 <%= csrf_meta_tag %>
</head>
<body class="<%= controller.controller_name %>">

 <div id="banner">
   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Bands for You</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark" href="#"><%= link_to 'Main Store', store_path %></span>
      <span class="p-2 text-dark" href="#"><%= link_to "About us", store_about_path %></span>
      <% if session[:user_id] %>
        <span class="p-2 text-dark" href="#"><%= link_to 'Orders', orders_path %></span>
        <span class="p-2 text-dark" href="#"><%= link_to 'Products', products_path %></span>
        <span class="p-2 text-dark" href="#"><%= link_to 'Users', users_path %></span>
        <span class="btn btn-primary" href="#"><%= button_to 'Logout', logout_path, method: :delete %></span>
      <% end %>
    </nav>
  </div>
 </div>

 <div id="columns" class="container">
    <div class="row">
      <% if @cart %>
      <div class="col-md-3" id="cart"><%= render @cart%></div>
      <% end %>
      <div class="col-md-9"><%= yield %></div>
    </div>
 </div>


</body>
</html>